package com.chatapp.android.core.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {
    /**
     * Getter & setter method for specific event
     */
    private Long id;
    private String name;
    private String picUrl;
    private String status;
    private String msisdn;
    private Boolean currentUser;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String name, String picUrl, String status, String msisdn, Boolean currentUser) {
        this.id = id;
        this.name = name;
        this.picUrl = picUrl;
        this.status = status;
        this.msisdn = msisdn;
        this.currentUser = currentUser;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPicUrl() {
        return picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getMsisdn() {
        return msisdn;
    }

    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn;
    }

    public Boolean getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(Boolean currentUser) {
        this.currentUser = currentUser;
    }

}
